"""empty message

Revision ID: 552080c679a1
Revises: 
Create Date: 2019-12-07 18:15:08.829887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '552080c679a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_USERS', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('TB_USERS', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_USERS', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('TB_USERS', 'password_hash')
    # ### end Alembic commands ###
