"""empty message

Revision ID: fc8ed2121a88
Revises: 552080c679a1
Create Date: 2019-12-07 23:29:39.261748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc8ed2121a88'
down_revision = '552080c679a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_POSTS', sa.Column('article', sa.Text(), nullable=True))
    op.add_column('TB_POSTS', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='TB_POSTS')
    op.create_unique_constraint(None, 'TB_POSTS', ['title'])
    op.drop_column('TB_POSTS', 'name')
    op.drop_column('TB_POSTS', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_POSTS', sa.Column('test', mysql.TEXT(), nullable=True))
    op.add_column('TB_POSTS', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'TB_POSTS', type_='unique')
    op.create_index('name', 'TB_POSTS', ['name'], unique=True)
    op.drop_column('TB_POSTS', 'title')
    op.drop_column('TB_POSTS', 'article')
    # ### end Alembic commands ###
